### PR TITLE
Get browser-sync to watch for changes also in the compiled css folder

### PR DESCRIPTION
**Pull request by mrzool**
So that the browser gets refreshed also when editing the css, not only when editing index.html

### CODE REVIEW

**Comment by mrmrs** [comment]
You wouldn't want to update on every file change. For instance this will reload the browser if you update the css source and after compilation. It would be better to be explicit with only updating after the compiled css has changed.

**Comment by mrzool** [comment]
That's true. Looking better now?

**Comment by mrmrs** [comment]
Looks good to me - thanks!

**Comment by mrzool** [comment]
Glad to help!

**Pull request merged**
